import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

async function source(path){return readFile(new URL(`../${path}`,import.meta.url),'utf8')}

test('canonical Office interop pipeline enriches Word and Excel review provenance before synchronization',async()=>{
  const text=await source('src/officeInteropImport.ts')
  assert.match(text,/preserveDocxCommentMetadata/)
  assert.match(text,/const withWordComments=await preserveDocxCommentMetadata\(workspace,input,fileName,parsed\)/)
  assert.match(text,/preserveXlsxCommentMetadata/)
  assert.match(text,/preserveXlsxThreadedCommentMetadata/)
  assert.match(text,/preserveXlsxSheetVisibility\(workspace,input,fileName,withWordComments\)/)
  assert.match(text,/const withComments=await preserveXlsxCommentMetadata\(workspace,input,fileName,withLinks\)/)
  assert.match(text,/const withThreads=await preserveXlsxThreadedCommentMetadata\(workspace,input,fileName,withComments\)/)
  assert.match(text,/preserveXlsxSharedFormulaMetadata\(input,fileName,withThreads\)/)
})

test('classic note provenance retains source-cell identity through parser and runtime codec',async()=>{
  const parser=await source('src/xlsxCommentImport.ts')
  const codec=await source('src/importedTableCodec.ts')
  const review=await source('src/importedDataReview.ts')
  assert.match(parser,/sourceRef:ref/)
  assert.match(codec,/sourceRef must be an A1 cell reference/)
  assert.match(review,/classicNoteSourceReviewId/)
  assert.match(review,/comment\.sourceRef/)
})

test('Word comments become source-only workspace review anchored to imported semantic blocks',async()=>{
  const parser=await source('src/docxCommentImport.ts')
  const codec=await source('src/workspaceReviewCodec.ts')
  const reviews=await source('src/workspaceReviews.ts')
  const inbox=await source('src/workspaceReviewInbox.ts')
  const context=await source('src/components/ContextPanel.tsx')
  const search=await source('src/searchIndex.ts')
  assert.match(parser,/parseDocxComments/)
  assert.match(parser,/parseDocxCommentParagraphAnchors/)
  assert.match(parser,/sourceOnly:true/)
  assert.match(parser,/kind:'word-comment'/)
  assert.match(codec,/word-comment/)
  assert.match(codec,/Source-only workspace reviews/)
  assert.match(reviews,/if\(review\.sourceOnly\)return false/)
  assert.match(inbox,/origin:'imported-word'/)
  assert.match(context,/Word source comment/)
  assert.match(search,/Source review/)
})

test('semantic history uses the review-aware workspace comparator and distinguishes source from native review',async()=>{
  const browser=await source('src/components/HistoryBrowser.tsx')
  const revert=await source('src/revert.ts')
  const compare=await source('src/workspaceReviewCompare.ts')
  assert.match(browser,/compareWorkspaceStatesWithReview/)
  assert.doesNotMatch(browser,/compareWorkspaceStates\(selected\.transaction\.before/)
  assert.match(revert,/compareWorkspaceStatesWithReview/)
  assert.match(compare,/getWorkspaceReviews/)
  assert.match(compare,/sourceOnly\?'Source review':'Frame review'/)
})

test('imported Data cells render source review and canonical native workspace review provenance',async()=>{
  const text=await source('src/components/ImportedTablesPanel.tsx')
  assert.match(text,/getImportedTableComment/)
  assert.match(text,/getImportedTableThread/)
  assert.match(text,/getWorkspaceReviews/)
  assert.match(text,/sourceReview\.kind!=='word-comment'/)
  assert.match(text,/imported-note-badge/)
  assert.match(text,/imported-thread-badge/)
  assert.match(text,/imported-frame-review-badge/)
  assert.match(text,/MessageSquareText/)
})

test('Office export preflight exposes source review and native review counts without conflating Word provenance',async()=>{
  const assessment=await source('src/officeExportAssessment.ts')
  const page=await source('src/OfficeExportPage.tsx')
  assert.match(assessment,/sourceReviewComments/)
  assert.match(assessment,/reviewNoteCells/)
  assert.match(assessment,/reviewThreadCells/)
  assert.match(assessment,/threadedComments/)
  assert.match(assessment,/promotedReviewItems/)
  assert.match(assessment,/filter\(\(review\)=>!review\.sourceOnly\)/)
  assert.match(assessment,/rather than flattened into legacy notes/)
  assert.match(page,/Word source comments/)
  assert.match(page,/Legacy review notes/)
  assert.match(page,/Source review threads/)
  assert.match(page,/assessment\.xlsx\.promotedReviewItems/)
})

test('canonical native review storage is workspace-level while table-owned promoted reviews remain migration-only',async()=>{
  const workspaceReviews=await source('src/workspaceReviews.ts')
  const commandCodec=await source('src/commandCodec.ts')
  const tableCodec=await source('src/importedTableCodec.ts')
  const semanticCommands=await source('src/semanticCommands.ts')
  assert.match(workspaceReviews,/workspaceReviews/)
  assert.match(workspaceReviews,/materializeWorkspaceReviews/)
  assert.match(workspaceReviews,/legacyTableReviews/)
  assert.match(commandCodec,/review\.workspace\.replace/)
  assert.match(commandCodec,/parseWorkspaceReviewRecord/)
  assert.match(semanticCommands,/case 'review\.workspace\.replace'/)
  assert.match(tableCodec,/promotedReviews/)
  assert.match(tableCodec,/cannot store Word provenance/)
})

test('unified Context review inbox opens a configurable promotion editor for Excel source provenance',async()=>{
  const inbox=await source('src/workspaceReviewInbox.ts')
  const context=await source('src/components/ContextPanel.tsx')
  const editor=await source('src/components/ReviewPromotionDialog.tsx')
  const promotion=await source('src/reviewPromotion.ts')
  const sync=await source('src/officeImportSync.ts')
  assert.match(inbox,/source-thread/)
  assert.match(inbox,/frame-data/)
  assert.match(context,/ReviewPromotionDialog/)
  assert.match(context,/setPromotionSourceId\(item\.id\)/)
  assert.match(context,/>Promote</)
  assert.match(editor,/planPromoteSourceReview/)
  assert.match(editor,/\['task','comment','approval'\]/)
  assert.match(editor,/Promoted review owner/)
  assert.match(editor,/Promoted review body/)
  assert.match(promotion,/body\?:string/)
  assert.match(promotion,/explicit owner/)
  assert.match(promotion,/review\.workspace\.replace/)
  assert.match(promotion,/sourceOnly/)
  assert.match(sync,/getWorkspaceReviews/)
  assert.match(sync,/findSourceReviewCell/)
  assert.match(sync,/setReviewCommand/)
  assert.match(sync,/withoutLegacyReviews/)
})

test('archived native review can be explicitly relinked to ranked refreshed source review',async()=>{
  const inbox=await source('src/workspaceReviewInbox.ts')
  const context=await source('src/components/ContextPanel.tsx')
  const editor=await source('src/components/ReviewRelinkDialog.tsx')
  const planner=await source('src/reviewRelink.ts')
  assert.match(inbox,/archived:boolean/)
  assert.match(inbox,/archivedNativeOpen/)
  assert.match(context,/ReviewRelinkDialog/)
  assert.match(context,/setRelinkReviewId\(item\.id\)/)
  assert.match(context,/>Relink</)
  assert.match(editor,/listReviewRelinkCandidates/)
  assert.match(editor,/planRelinkPromotedReview/)
  assert.match(editor,/matchHints/)
  assert.match(planner,/occupiedSourceKeys/)
  assert.match(planner,/same source text/)
  assert.match(planner,/same source identity/)
  assert.match(planner,/review archive/)
})
