import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, CheckCircle2, CopyCheck, FileDiff, FileSearch, ShieldCheck, UploadCloud, XCircle } from 'lucide-react'
import { cloneSeedWorkspace } from './model'
import { simulateOfficeMigration, type OfficeMigrationSimulation } from './officeMigrationSimulation'
import { hydrateWorkspaceSession, LEGACY_WORKSPACE_STORAGE_KEY, SESSION_STORAGE_KEY } from './sessionStore'
import { createVersionedWorkspaceSession } from './versioning'

function loadWorkspace(){try{const session=localStorage.getItem(SESSION_STORAGE_KEY);if(session)return hydrateWorkspaceSession(JSON.parse(session)).present;const legacy=localStorage.getItem(LEGACY_WORKSPACE_STORAGE_KEY);return hydrateWorkspaceSession(null,legacy?JSON.parse(legacy):cloneSeedWorkspace()).present}catch{return createVersionedWorkspaceSession(cloneSeedWorkspace()).present}}
function home(){window.location.assign('/')}

export default function OfficeMigrationPage(){
  const workspace=useMemo(loadWorkspace,[])
  const [simulation,setSimulation]=useState<OfficeMigrationSimulation|null>(null)
  const [running,setRunning]=useState(false)
  const [error,setError]=useState<string|null>(null)
  const chooseFiles=()=>{const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='.docx,.pptx,.xlsx';input.onchange=async()=>{const files=[...(input.files??[])];if(!files.length)return;setRunning(true);setError(null);try{const prepared=[];for(const file of files)prepared.push({name:file.name,bytes:new Uint8Array(await file.arrayBuffer())});setSimulation(await simulateOfficeMigration(workspace,prepared))}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setRunning(false)}};input.click()}
  const applied=simulation?.files.filter((item)=>item.status==='applied').length??0,duplicates=simulation?.files.filter((item)=>item.status==='duplicate-skipped').length??0,failed=simulation?.files.filter((item)=>item.status==='failed').length??0
  return <main className="office-migration-page">
    <header className="office-migration-header"><div className="office-migration-brand"><span>F</span><strong>Frame</strong></div><button className="secondary-button" onClick={home}><ArrowLeft size={14}/> Back to workspace</button></header>
    <section className="office-migration-intro"><div className="office-migration-intro-icon"><ShieldCheck size={24}/></div><span>OFFICE MIGRATION REHEARSAL</span><h1>See the semantic migration before you do it</h1><p>Frame secure-plans each DOCX, PPTX and XLSX into a cloned versioned session. No workspace changes are applied. Duplicate content is skipped by hash, while revisions, fidelity warnings, formula debt and imported review work are surfaced together.</p><button className="primary-button" onClick={chooseFiles} disabled={running}><UploadCloud size={15}/>{running?'Simulating…':'Choose Office files'}</button>{error&&<div className="office-migration-error"><XCircle size={13}/>{error}</div>}</section>
    {!simulation?<section className="office-migration-empty"><FileSearch size={24}/><strong>No rehearsal yet</strong><span>Select one or more Office files to inspect their combined migration effect without mutating Frame.</span></section>:<>
      <section className="office-migration-facts"><Fact label="Applied in memory" value={applied}/><Fact label="Duplicate-skipped" value={duplicates}/><Fact label="Failed" value={failed}/><Fact label="Simulated transactions" value={simulation.session.past.length}/><Fact label="Formula candidates ready" value={`${simulation.formulaTranslation.ready}/${simulation.formulaTranslation.total}`}/><Fact label="Imported review notes" value={simulation.importedReview.total}/></section>
      <section className="office-migration-results"><header><div><FileDiff size={15}/><div><span>FILES</span><strong>Migration classification</strong></div></div><small>{simulation.files.length} file{simulation.files.length===1?'':'s'}</small></header><div>{simulation.files.map((file)=><article key={file.name} className={file.status}><span className="office-migration-result-icon">{file.status==='applied'?<CheckCircle2 size={13}/>:file.status==='duplicate-skipped'?<CopyCheck size={13}/>:<XCircle size={13}/>}</span><div><strong>{file.name}</strong><span>{file.classification??file.status}{file.transactionCount!==undefined?` · ${file.transactionCount} semantic transactions`:''}</span>{file.error&&<small>{file.error}</small>}{file.warnings?.slice(0,3).map((warning)=><small key={warning}><AlertTriangle size={10}/>{warning}</small>)}</div></article>)}</div></section>
      <section className="office-migration-readiness"><header><span>POST-MIGRATION READINESS</span><h2>What still needs semantic work</h2></header><div className="office-migration-readiness-grid"><Readiness title="Foreign formulas" value={`${simulation.formulaTranslation.ready} ready`} detail={`${simulation.formulaTranslation.requiresModelPromotion} need model promotion · ${simulation.formulaTranslation.unsupported+simulation.formulaTranslation.missingField+simulation.formulaTranslation.missingTable} unresolved/unsupported`}/><Readiness title="Review provenance" value={`${simulation.importedReview.total} notes`} detail={`${simulation.importedReview.authors.length} authors · ${simulation.importedReview.tables.length} tables`}/><Readiness title="Office export" value={`${simulation.exportReview.warnings.length} notes`} detail={`${simulation.exportReview.exportAssessment.xlsx.suppressedHyperlinkCells} suppressed links · ${simulation.exportReview.exportAssessment.xlsx.suppressedDateLikeFormatCells} suppressed date styles`}/></div><div className="office-migration-warning-list">{simulation.exportReview.warnings.slice(0,8).map((warning)=><div key={warning}><AlertTriangle size={11}/>{warning}</div>)}</div></section>
    </>}
  </main>
}
function Fact({label,value}:{label:string;value:string|number}){return <div className="office-migration-fact"><span>{label}</span><strong>{value}</strong></div>}
function Readiness({title,value,detail}:{title:string;value:string;detail:string}){return <article><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>}
