import { executeVersionedWorkspaceCommand, type VersionedWorkspaceSession, type VersionedWorkspaceTransaction } from './versioning.ts'
import type { VersionedWorkspaceCommand } from './semanticCommands.ts'
import { compareWorkspaceStates } from './workspaceCompare.ts'
export type RevertConflict={objectId:string;field:string;message:string}
export type RevertPlan={transaction:VersionedWorkspaceTransaction;canRevert:boolean;inverseCommand:VersionedWorkspaceCommand|null;diffs:ReturnType<typeof compareWorkspaceStates>;conflicts:RevertConflict[]}
const conflict=(objectId:string,field:string,message:string):RevertConflict=>({objectId,field,message})
export function planTransactionRevert(session:VersionedWorkspaceSession,transactionId:string):RevertPlan{
  const transaction=session.past.find((x)=>x.id===transactionId);if(!transaction)throw new Error(`Unknown applied transaction: ${transactionId}`);const conflicts:RevertConflict[]=[];let inverseCommand:VersionedWorkspaceCommand|null=null;const current=session.present,command=transaction.command
  switch(command.type){
    case'region.update':{const before=transaction.before.regions.find((x)=>x.id===command.regionId),after=transaction.after.regions.find((x)=>x.id===command.regionId),now=current.regions.find((x)=>x.id===command.regionId);if(!before||!after||!now)conflicts.push(conflict(`region:${command.regionId}`,String(command.field),'Region no longer exists'));else if(!Object.is(now[command.field],after[command.field]))conflicts.push(conflict(`region:${command.regionId}`,String(command.field),'Field changed again after this transaction'));else inverseCommand={type:'region.update',regionId:command.regionId,field:command.field,value:before[command.field]};break}
    case'decision.status':{const before=transaction.before.decisions.find((x)=>x.id===command.decisionId),after=transaction.after.decisions.find((x)=>x.id===command.decisionId),now=current.decisions.find((x)=>x.id===command.decisionId);if(!before||!after||!now)conflicts.push(conflict(`decision:${command.decisionId}`,'status','Decision no longer exists'));else if(now.status!==after.status)conflicts.push(conflict(`decision:${command.decisionId}`,'status','Decision status changed again after this transaction'));else inverseCommand={type:'decision.status',decisionId:command.decisionId,status:before.status};break}
    case'document.append':if(current.document.body!==transaction.after.document.body)conflicts.push(conflict('document:strategy','body','Document body changed after the append'));else inverseCommand={type:'document.update',field:'body',value:transaction.before.document.body};break
    case'document.update':if(current.document[command.field]!==transaction.after.document[command.field])conflicts.push(conflict('document:strategy',String(command.field),'Document field changed again after this transaction'));else inverseCommand={type:'document.update',field:command.field,value:transaction.before.document[command.field]};break
    case'metric.formula':{const before=transaction.before.metrics.find((x)=>x.id===command.metricId),after=transaction.after.metrics.find((x)=>x.id===command.metricId),now=current.metrics.find((x)=>x.id===command.metricId);if(!before||!after||!now)conflicts.push(conflict(`metric:${command.metricId}`,'formula','Metric no longer exists'));else if((now.formula??null)!==(after.formula??null))conflicts.push(conflict(`metric:${command.metricId}`,'formula','Formula changed again after this transaction'));else inverseCommand={type:'metric.formula',metricId:command.metricId,formula:before.formula??null,fallbackValue:before.value};break}
  }
  return{transaction,canRevert:conflicts.length===0&&inverseCommand!==null,inverseCommand,diffs:compareWorkspaceStates(transaction.before,transaction.after),conflicts}
}
export function revertVersionedTransaction(session:VersionedWorkspaceSession,transactionId:string){const plan=planTransactionRevert(session,transactionId);if(!plan.canRevert||!plan.inverseCommand)return{session,plan};return{plan,session:executeVersionedWorkspaceCommand(session,plan.inverseCommand,{kind:'revert',reverts:transactionId})}}
export function getTransactionDiff(transaction:VersionedWorkspaceTransaction){return compareWorkspaceStates(transaction.before,transaction.after)}
