import { hydrateWorkspace, type WorkspaceMutationResult, type WorkspaceState, type WorkspaceTransaction } from './model.ts'
import { runVersionedCommand, versionedCommandIsNoop, type VersionedWorkspaceCommand } from './semanticCommands.ts'

export type VersionedWorkspaceTransaction = Omit<WorkspaceTransaction,'command'> & { command:VersionedWorkspaceCommand; revision:number; createdAt:string; eventId:string; kind:'change'|'revert'; reverts?:string }
export type VersionedWorkspaceSession = { present:WorkspaceState; past:VersionedWorkspaceTransaction[]; future:VersionedWorkspaceTransaction[]; ledger:VersionedWorkspaceTransaction[]; nextRevision:number }
export type VersionHistoryStatus = 'current'|'applied'|'undone'|'branch'
export type VersionSnapshot = { id:string; revision:number; label:string; status:VersionHistoryStatus|'base'; workspace:WorkspaceState; transactionId?:string }

function nowIso(){return new Date().toISOString()}
function uniqueId(prefix:string){const uuid=globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;return `${prefix}:${uuid}`}
function stampResult(result:WorkspaceMutationResult,eventId:string,changedAt?:string){const event={...result.event,id:eventId,changedAt:changedAt??result.event.changedAt};const workspace={...result.workspace,history:result.workspace.history.map((item,index)=>index===0?event:item)};return{...result,workspace,event}}
export function createVersionedWorkspaceSession(workspace:WorkspaceState):VersionedWorkspaceSession{return{present:workspace,past:[],future:[],ledger:[],nextRevision:1}}
export function executeVersionedWorkspaceCommand(session:VersionedWorkspaceSession,command:VersionedWorkspaceCommand,metadata?:{kind?:'change'|'revert';reverts?:string;createdAt?:string}):VersionedWorkspaceSession{
  if(versionedCommandIsNoop(session.present,command))return session
  const revision=session.nextRevision,createdAt=metadata?.createdAt??nowIso(),eventId=uniqueId('event');const result=stampResult(runVersionedCommand(session.present,command),eventId,command.changedAt)
  const transaction:VersionedWorkspaceTransaction={id:uniqueId('transaction'),revision,createdAt,eventId:result.event.id,command,summary:result.event.summary,before:structuredClone(session.present),after:structuredClone(result.workspace),kind:metadata?.kind??'change',reverts:metadata?.reverts}
  return{present:result.workspace,past:[...session.past,transaction].slice(-100),future:[],ledger:[...session.ledger,transaction].slice(-500),nextRevision:revision+1}
}
export function undoVersionedWorkspaceSession(session:VersionedWorkspaceSession):VersionedWorkspaceSession{const transaction=session.past.at(-1);if(!transaction)return session;return{...session,present:structuredClone(transaction.before),past:session.past.slice(0,-1),future:[transaction,...session.future].slice(0,100)}}
export function redoVersionedWorkspaceSession(session:VersionedWorkspaceSession):VersionedWorkspaceSession{const transaction=session.future[0];if(!transaction)return session;return{...session,present:structuredClone(transaction.after),past:[...session.past,transaction].slice(-100),future:session.future.slice(1)}}
export function getVersionedHistory(session:VersionedWorkspaceSession){const applied=new Set(session.past.map((x)=>x.id)),undone=new Set(session.future.map((x)=>x.id)),current=session.past.at(-1)?.id;return[...session.ledger].sort((a,b)=>b.revision-a.revision).map((transaction)=>({transaction,status:transaction.id===current?'current' as const:applied.has(transaction.id)?'applied' as const:undone.has(transaction.id)?'undone' as const:'branch' as const}))}
export function collectVersionSnapshots(session:VersionedWorkspaceSession):VersionSnapshot[]{const ordered=[...session.ledger].sort((a,b)=>a.revision-b.revision),history=new Map(getVersionedHistory(session).map((x)=>[x.transaction.id,x.status])),base=ordered[0]?.before??session.present;return[{id:'version:0',revision:0,label:'Initial workspace',status:'base',workspace:structuredClone(base)},...ordered.map((transaction)=>({id:`version:${transaction.revision}`,revision:transaction.revision,label:`v${transaction.revision} · ${transaction.summary}`,status:history.get(transaction.id)??'branch',workspace:structuredClone(transaction.after),transactionId:transaction.id}))]}
export function hydrateVersionedWorkspaceSession(value:Partial<VersionedWorkspaceSession>|null|undefined,fallbackWorkspace?:WorkspaceState):VersionedWorkspaceSession{
  const present=hydrateWorkspace(value?.present??fallbackWorkspace),supplied=value?.ledger??[],all=supplied.length?supplied:[...(value?.past??[]),...(value?.future??[])],usedRevisions=new Set<number>(),usedIds=new Set<string>();let fallbackRevision=1
  const normalize=(transaction:VersionedWorkspaceTransaction):VersionedWorkspaceTransaction=>{const explicit=Number(transaction.revision),fromId=Number(transaction.id?.match(/(\d+)$/)?.[1]);let revision=Number.isFinite(explicit)&&explicit>0?explicit:fromId;if(!Number.isFinite(revision)||revision<=0||usedRevisions.has(revision)){while(usedRevisions.has(fallbackRevision))fallbackRevision++;revision=fallbackRevision}usedRevisions.add(revision);fallbackRevision=Math.max(fallbackRevision,revision+1);const modern=typeof transaction.id==='string'&&/^transaction:[0-9a-f-]{36}$/i.test(transaction.id),candidate=modern?transaction.id:uniqueId('transaction'),id=usedIds.has(candidate)?uniqueId('transaction'):candidate;usedIds.add(id);return{...transaction,id,revision,eventId:typeof transaction.eventId==='string'&&/^event:[0-9a-f-]{36}$/i.test(transaction.eventId)?transaction.eventId:uniqueId('event'),createdAt:transaction.createdAt??nowIso(),kind:transaction.kind??'change',before:hydrateWorkspace(transaction.before),after:hydrateWorkspace(transaction.after)}}
  const normalized=all.map(normalize),byOriginal=new Map(all.map((item,index)=>[item,normalized[index]])),find=(transaction:VersionedWorkspaceTransaction)=>byOriginal.get(transaction)||normalized.find((item)=>item.id===transaction.id||(transaction.revision&&item.revision===transaction.revision))||normalized.find((item)=>item.summary===transaction.summary),past=(value?.past??[]).map(find).filter(Boolean) as VersionedWorkspaceTransaction[],future=(value?.future??[]).map(find).filter(Boolean) as VersionedWorkspaceTransaction[],ledger=normalized.sort((a,b)=>a.revision-b.revision).slice(-500),inferred=Math.max(0,...ledger.map((x)=>x.revision))+1
  return{present,past:past.slice(-100),future:future.slice(0,100),ledger,nextRevision:Math.max(value?.nextRevision??1,inferred)}
}
